### ISSUE TITLE
合成时报错 can't open file 'main.py' 是为什么?

### ISSUE THREAD

**Issue by m-v-priest** [dream80/DeepFaceLab_Colab#10]
合成时报错, 
[Errno 2] No such file or directory: '/content/drive/My Drive/DeepFaceLab/DeepFaceLab_Colab/'
/content
python3: can't open file 'main.py': [Errno 2] No such file or directory

----

蛮奇怪的, 后来不知怎么, 这个main.py文件又存在了. 可能是谷歌云端加载慢的问题还是怎的?   又能执行了

**Comment by hiqatgh** [comment]
> 合成时报错, [Errno 2] No such file or directory: '/content/drive/My Drive/DeepFaceLab/DeepFaceLab_Colab/' /content python3: can't open file 'main.py': [Errno 2] No such file or directory
> 
> 蛮奇怪的, 后来不知怎么, 这个main.py文件又存在了. 可能是谷歌云端加载慢的问题还是怎的? 又能执行了

没挂载硬盘，分配的设备经常掉线
