### ISSUE TITLE
DeepFaceLab_Colab_V4.ipynb的疑問

### ISSUE THREAD

**Issue by iam-YZ** [dream80/DeepFaceLab_Colab#18]
您好，對**DeepFaceLab_Colab_V4.ipynb的第三步. 提取脸部功能**有疑問，
aligned目录下剛提取到的图片素材都還未排序就直接打包成faceset.pak文件了

**Comment by iam-YZ** [comment]
可不可以把  **第三步. 提取脸部**  中的三個小功能( 分解视频，提取人脸，打包素材) 分別獨立出來，
目前應該是打包素材的代碼寫在一起，所以造成這個問題

**Comment by hiqatgh** [comment]
> 可不可以把 **第三步. 提取脸部** 中的三個小功能( 分解视频，提取人脸，打包素材) 分別獨立出來， 目前應該是打包素材的代碼寫在一起，所以造成這個問題

可以啊，代码都包含在单元格里面，你可以自己提炼、修改

**Comment by dream80** [comment]
本来是分开，后来合并了。如果需要处理图片，可以用底部的“解包” 解开，处理完之后再次“打包”。不打包也没关系。但是colab上加载会超慢。
