### ISSUE TITLE
Training results in AttributeError: 'SAEModel' object has no attribute 'generator_list'

### ISSUE THREAD

**Issue by chirico85** [dream80/DeepFaceLab_Colab#19]
## Expected behavior

Run Training without errors.

## Actual behavior

```
Error: 'SAEModel' object has no attribute 'generator_list'
Traceback (most recent call last):
  File "\DeepFaceLab_Colab\mainscripts\Trainer.py", line 46, in trainerThread
    model = models.import_model(model_class_name)(
  File "\DeepFaceLab_Colab\models\ModelBase.py", line 209, in __init__
    if self.generator_list is None:
AttributeError: 'SAEModel' object has no attribute 'generator_list'
```

## Steps to reproduce

running following code:
`python main.py train --training-data-src-dir ../workspace/data_src/aligned --training-data-dst-dir ../workspace/data_dst/aligned --model-dir ../workspace/model --model SAE --no-preview`

## Other relevant information
- **Operating system and version:** Windows 10
- **Python version:** 3.8

**Comment by Suv00m** [comment]
how to solve it then
