### ISSUE TITLE
能否加入使用tpu来跑模型？

### ISSUE THREAD

**Issue by il123456** [dream80/DeepFaceLab_Colab#2]
我想用colab的tpu来跑模型,不知道要怎么改，能否加入调用tpu的代码

**Comment by dream80** [comment]
这个，，，我也不清楚！


 
---原始邮件---
发件人: "il123456"<notifications@github.com>
发送时间: 2019年5月11日(星期六) 下午4:39
收件人: "dream80/DeepFaceLab_Colab"<DeepFaceLab_Colab@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [dream80/DeepFaceLab_Colab] 能否加入使用tpu来跑模型？ (#2)



我想用colab的tpu来跑模型,不知道要怎么改，能否加入调用tpu的代码
