### ISSUE TITLE
源软件包已经不能正确安装了

### ISSUE THREAD

**Issue by hiqatgh** [dream80/DeepFaceLab_Colab#25]
除了last，其他版本全部不正常。last虽然能用，但是用不了gpu，只能用cpu，cpu太慢了。希望作者修一下

**Comment by dream80** [comment]
😃能不能用GPU不在我的控制范围之内。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月19日(周三) 晚上6:43
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [dream80/DeepFaceLab_Colab] 源软件包已经不能正确安装了 (Issue #25)




 
除了last，其他版本全部不正常。last虽然能用，但是用不了gpu，只能用cpu，cpu太慢了。希望作者修一下

**Comment by hiqatgh** [comment]
> 😃能不能用GPU不在我的控制范围之内。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年10月19日(周三) 晚上6:43 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [dream80/DeepFaceLab_Colab] 源软件包已经不能正确安装了 (Issue #25) 除了last，其他版本全部不正常。last虽然能用，但是用不了gpu，只能用cpu，cpu太慢了。希望作者修一下 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

不是免费gpu的免费时限问题，是last下载的版本确实没办法调用gpu。。所以我就针对v3.07.20修了一下，真的修好了。
是numpy、scipy两个程序版本太低造成的问题。安装完deepfacelab后重装一下这两个程序就好了。
重装代码：

!pip uninstall scipy
!pip install scipy

pip uninstall numpy
!pip install numpy

**Comment by dream80** [comment]
numpy的问题我已经更新过了，Last不能调用GPU这个问题，我检查下。

**Comment by hiqatgh** [comment]
又有版本对不上的软件了。。v3.07.20

错误信息：
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
xarray-einstats 0.2.2 requires numpy>=1.21, but you have numpy 1.19.3 which is incompatible.
tensorflow 2.9.2 requires numpy>=1.20, but you have numpy 1.19.3 which is incompatible.
tensorflow 2.9.2 requires tensorflow-estimator<2.10.0,>=2.9.0rc0, but you have tensorflow-estimator 2.10.0 which is incompatible.
tensorflow-gpu 2.4.0 requires absl-py~=0.10, but you have absl-py 1.3.0 which is incompatible.
tensorflow-gpu 2.4.0 requires tensorflow-estimator<2.5.0,>=2.4.0rc0, but you have tensorflow-estimator 2.10.0 which is incompatible.
plotnine 0.8.0 requires scipy>=1.5.0, but you have scipy 1.4.1 which is incompatible.
jaxlib 0.3.22+cuda11.cudnn805 requires numpy>=1.20, but you have numpy 1.19.3 which is incompatible.
jaxlib 0.3.22+cuda11.cudnn805 requires scipy>=1.5, but you have scipy 1.4.1 which is incompatible.
jax 0.3.23 requires numpy>=1.20, but you have numpy 1.19.3 which is incompatible.
jax 0.3.23 requires scipy>=1.5, but you have scipy 1.4.1 which is incompatible.
cupy-cuda11x 11.0.0 requires numpy<1.26,>=1.20, but you have numpy 1.19.3 which is incompatible.
cmdstanpy 1.0.7 requires numpy>=1.21, but you have numpy 1.19.3 which is incompatible.
Successfully installed numpy-1.19.3 scipy-1.4.1
WARNING: The following packages were previously imported in this runtime:
  [numpy]
You must restart the runtime in order to use newly installed versions.

**Comment by dream80** [comment]
修复了安装过程红色警告的问题和 Last版本无法调用GPU的问题。我只做了常规流程测试，你可以点击最新版，运行看是否还存在你说的问题。如果还存在问题，可以反馈在这里，如果没有其他问题，我就关闭这个issues了。

**Comment by hiqatgh** [comment]
> 修复了安装过程红色警告的问题和 Last版本无法调用GPU的问题。我只做了常规流程测试，你可以点击最新版，运行看是否还存在你说的问题。如果还存在问题，可以反馈在这里，如果没有其他问题，我就关闭这个issues了。

昨天用出了一堆问题，今天用又正常了。我还是v3.07.20，重装numpy、scipy就能用。last依然用不了gpu

**Comment by hiqatgh** [comment]
升级这两软件就没问题了：
!pip install -U numpy scipy
