### ISSUE TITLE
dfl-colab broke again :(

### ISSUE THREAD

**Issue by GHnewbie2022** [dream80/DeepFaceLab_Colab#27]
![圖片](https://user-images.githubusercontent.com/116427364/235331514-f79be623-b1f4-40d6-9d48-74ccc7400b16.png)
![圖片](https://user-images.githubusercontent.com/116427364/235331583-29855681-1dae-4822-9495-bef7f6cf0c8a.png)
![圖片](https://user-images.githubusercontent.com/116427364/235331585-e095586b-6ebc-4b68-8f2f-038dc263ed91.png)

## Expected behavior

原本可以正常使用，照步驟循序漸進安裝好就可以訓練

## Actual behavior

安裝步驟卡很久並且跳錯，最後在訓練步驟無法正常執行

## Steps to reproduce

一步一步照著點就可以重現了

## Other relevant information

似乎是因為google colab官方又有所變動的關係，導致notebook故障

**Comment by dream80** [comment]
我随便安装个依赖都卡半天...

**Comment by dream80** [comment]
能用的cv版本装不上，能装上的cv版本不能用，有点无解了。

**Comment by dream80** [comment]
已修复
