### ISSUE TITLE
Merge 2 trained models

### ISSUE THREAD

**Issue by kheniparth** [dream80/DeepFaceLab_Colab#4]
I read online that we can reuse the same model with different faces as well. 

So my question is that, is there any way we could mege two different trained models together by any chance?

Sorry if this a silly question to ask :stuck_out_tongue_winking_eye:

Thank you

**Comment by dream80** [comment]
It is feasible to reuse the model 。You can train a model first and continue to use this model in the next group of material.

**Comment by kheniparth** [comment]
Thank you for your reply. I tried to train the same model with a different dataset and it worked.

But my question was that how to combine 2 separately trained models? 
It is not like that I have trained one model and I want to use different datasets. Right now I have 2 trained models those were trained on different faces and now I want to combine them and make one model so I can train it further. I hope this clarifies my question. :)
